# server port
server:
  port: 8080

# datasource
spring:
  datasource:
    url: jdbc:mysql://rm-wz98eu202hx5fv84gzo.mysql.rds.aliyuncs.com:3306/recipe
    username: root
    password: qXd8b#5Y%!e2P4PcMR9zPj5XPA**
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid
    initialSize: 10
    minIdle: 5
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    rollback-on-commit-failure: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j2,config
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

  # redis
  redis:
    host: 120.77.180.200
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 20
        max-wait: -1
    password: ^P9eVPp737vGjpmgqo#R3#&F%s7i

  # mail
  mail:
    host: smtp.163.com
    username: kkkk2077@163.com
    password: SEZZOMBFXMJQJSTA
    port: 587
    protocol: smtp
    properties.mail.display.sendmail: Springboot
    properties.mail.display.sendname: COMP3900-YYDS
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          timeout: 6000
          connectiontimeout: 6000
          writetimeout: 6000
          ssl: true
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory


# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# Minio
#minio:
#  endpoint: http://120.77.180.200:9000
#  accessKey: minioadmin
#  secretKey: minioadmin
#  bucket:
#    profile:
#      photo: profile-photo
#    recipe:
#      photo: recipe-photo
#      video: recipe-video

# actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

    jmx:
      domain: org.springframework.boot
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

aliyun:
  oss:
    bucketName: comp3900-w18a-yyds
    accessKeyId: LTAI5tMGGufMdDKS2SiyQXdJ
    accessKeySecret: B3FaLdpLAQFFZ9gaWqyCFgaNdA6JtR
    endpoint: oss-accelerate.aliyuncs.com